<?php

/**
 * BasePageAbstract
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title_tag
 * @property string $description_tag
 * @property string $keywords_tag
 * 
 * @method string       getTitleTag()        Returns the current record's "title_tag" value
 * @method string       getDescriptionTag()  Returns the current record's "description_tag" value
 * @method string       getKeywordsTag()     Returns the current record's "keywords_tag" value
 * @method PageAbstract setTitleTag()        Sets the current record's "title_tag" value
 * @method PageAbstract setDescriptionTag()  Sets the current record's "description_tag" value
 * @method PageAbstract setKeywordsTag()     Sets the current record's "keywords_tag" value
 * 
 * @package    Base
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePageAbstract extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page_abstract');
        $this->hasColumn('title_tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description_tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords_tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}