<?php

/**
 * BaseSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_enabled
 * @property boolean $show_in_menu
 * @property string $route
 * @property string $title
 * @property clob $text
 * @property integer $order
 * 
 * @method boolean getIsEnabled()    Returns the current record's "is_enabled" value
 * @method boolean getShowInMenu()   Returns the current record's "show_in_menu" value
 * @method string  getRoute()        Returns the current record's "route" value
 * @method string  getTitle()        Returns the current record's "title" value
 * @method clob    getText()         Returns the current record's "text" value
 * @method integer getOrder()        Returns the current record's "order" value
 * @method Site    setIsEnabled()    Sets the current record's "is_enabled" value
 * @method Site    setShowInMenu()   Sets the current record's "show_in_menu" value
 * @method Site    setRoute()        Sets the current record's "route" value
 * @method Site    setTitle()        Sets the current record's "title" value
 * @method Site    setText()         Sets the current record's "text" value
 * @method Site    setOrder()        Sets the current record's "order" value
 * 
 * @package    Base
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSite extends PageAbstract
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('site');
        $this->hasColumn('is_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('show_in_menu', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('route', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($sluggable0);
    }
}