<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $intro
 * @property clob $text
 * 
 * @method string getTitle() Returns the current record's "title" value
 * @method clob   getIntro() Returns the current record's "intro" value
 * @method clob   getText()  Returns the current record's "text" value
 * @method News   setTitle() Sets the current record's "title" value
 * @method News   setIntro() Sets the current record's "intro" value
 * @method News   setText()  Sets the current record's "text" value
 * 
 * @package    Base
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends PageAbstract
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('news');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('intro', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($sluggable0);
    }
}