<?php

/**
 * PageAbstractTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageAbstractTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageAbstractTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PageAbstract');
    }
}