<?php

/**
 * SiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTable extends PageAbstractTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Site');
    }
}