# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

site_show:
  url:        /:slug.html
  class:      sfDoctrineRoute
  param:      { module: site, action: show }
  options:    { model: Site, type: object }

# default rules
homepage:
  url:   /
  param: { module: site, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
