<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('news', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'keywords_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'intro' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'text' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'news_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('page_abstract', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'keywords_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('site', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'keywords_tag' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_enabled' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'show_in_menu' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'route' => 
             array(
              'type' => 'string',
              'length' => '30',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'text' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'order' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'site_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('news');
        $this->dropTable('page_abstract');
        $this->dropTable('site');
    }
}