PageAbstract:
  actAs:
    Timestampable:    ~
  columns:
    title_tag:        { type: string(255) }
    description_tag:  { type: string(255) }
    keywords_tag:     { type: string(255) }

Site:
  actAs:
    Sluggable:
      fields:         [title]
  inheritance:
    type:             concrete
    extends:          PageAbstract
  columns:
    is_enabled:       { type: boolean, default: false }
    show_in_menu:     { type: boolean, default: true }
    route:            { type: string(30) }
    title:            { type: string(255) }
    text:             { type: clob }
    order:            { type: integer }

News:
  actAs:
    Sluggable:
      fields:         [title]
  inheritance:
    type:             concrete
    extends:          PageAbstract
  columns:
    title:            { type: string(255) }
    intro:            { type: clob }
    text:             { type: clob }
